# Generated by Django 4.1 on 2022-10-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassProduct',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('ProductName', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ProductDescription', models.TextField(null=True, verbose_name='Descripcion')),
                ('ProductValue', models.FloatField(verbose_name='Valor')),
                ('ProductInventory', models.IntegerField(verbose_name='Inventario')),
                ('ProductImage', models.ImageField(null=True, upload_to='Images/', verbose_name='Imagen')),
            ],
        ),
    ]
